# based on https://nicolas-van.github.io/easy-markdown-to-github-pages/
plugins:
  - jekyll-relative-links
  - jekyll_pre
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
