# based on https://nicolas-van.github.io/easy-markdown-to-github-pages/
plugins:
  - jekyll-relative-links
  - jekyll_pre
  - jekyll-toc
  - moonwalk # dark, light mode
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

defaults:
  - scope:
      path: ""
    values:
      toc: true
